### ISSUE TITLE
Search icon out of place

### ISSUE THREAD

**Issue by GoogleCodeExporter** [archon810/androidpolice-public#36]
```
What steps will reproduce the problem?
1. Open the page

What is the expected output? What do you see instead?
Search icon is out of place

What operating system are you on?
Latest version of OSX Yosemite

What is your browser and its version?
Lastest version of Safari




```

Original issue reported on code.google.com by `austinle...@gmail.com` on 5 Feb 2015 at 8:42

Attachments:
- [Screen Shot 2015-02-05 at 3.40.38 PM.png](https://storage.googleapis.com/google-code-attachments/androidpolice/issue-36/comment-0/Screen Shot 2015-02-05 at 3.40.38 PM.png)

**Comment by archon810** [comment]
This should now be resolved.
