### ISSUE TITLE
Can't see comments in Opera Mini

### ISSUE THREAD

**Issue by GoogleCodeExporter** [archon810/androidpolice-public#51]
```
What steps will reproduce the problem?

1.Opening Any Android Police Article Using Opera Mini /New Opera Mini

What is the expected output? What do you see instead?

We need to see the comments, instead nothing is visible

What operating system are you on?

Android 4.4.4


What is your browser and its version?


Opera Mini 7.8.4. /New Opera Mini 8.0.1.801

Please provide any additional information below.

Please Look Into The Screen Shot !
```

Original issue reported on code.google.com by `kaushikb...@gmail.com` on 23 Apr 2015 at 4:34

Attachments:
- [Screenshot_2015-04-23-06-49-08.png](https://storage.googleapis.com/google-code-attachments/androidpolice/issue-51/comment-0/Screenshot_2015-04-23-06-49-08.png)

**Comment by kaushikb1996** [comment]
Looks like no one (Android Police Team) really cares !

**Comment by archon810** [comment]
We do care but our development resources have been tied up lately, so it's not just your bug that hasn't been fixed yet. 

The good news is that I've been working on getting more help, and we'll have several developers starting soon. Perhaps they can get this fixed after all, though I'm not sure that we will be able to he

**Comment by kaushikb1996** [comment]
Happy to know that :+1:

**Comment by archon810** [comment]
I tested in the latest Opera Mini, and comments are loading fine. Closing.
