### ISSUE TITLE
Trying to download files?

### ISSUE THREAD

**Issue by jtaz16** [archon810/androidpolice-public#74]
In chrome the I visit the site and it starts downloading multiple files at once. They are recipe files for some reason. Please fix this I like your site but I will not visit anymore if it is not fixed soon.

**Comment by archon810** [comment]
I am very sorry it's happening to you and other readers, and I've already alerted our advertising partners, but we haven't been able to figure out what's doing it or reproduce it reliably. We think it may be a weird Tyson/Knorr ad served via some major ad network. I hate that we even have to be in this ridiculous situation.

Hopefully, we'll figure out who's responsible soon.

**Comment by archon810** [comment]
The issues seems to have been resolved a while ago.
