### ISSUE TITLE
Search box text on AP homepage not visible on Safari

### ISSUE THREAD

**Issue by r0hanpn** [archon810/androidpolice-public#78]
#### Expected behavior
When you type anything in the search bar on the AndroidPolice.com homepage using the Safari web browser, it should show what is being typed.

#### Actual behavior
It doesn't show anything being typed, but the characters are being input, which is seen when you try to highlight that search box with the mouse pointer. Even if you type something and hit enter, it will search for what you typed. It just won't show you as you're typing it.

#### Steps to reproduce the problem
Open AndroidPolice.com in the Safari Web browser on a Mac (I'm on Safari 10.1 on macOS Sierra 10.2.4) and type anything in the search bar on the top right.
![android police search bar](https://cloud.githubusercontent.com/assets/27052922/24826919/a93ed354-1c5e-11e7-9e4c-1cdc9cb122e4.gif)

**Comment by archon810** [comment]
@r0hanpn A fix has been rolled out. Can you please retest?
