### ISSUE TITLE
website podcast not up to date. 

### ISSUE THREAD

**Issue by shaz213** [archon810/androidpolice-public#79]
#### Expected behavior
website podcast up to date.

#### Actual behavior
podcasts older, and missing numbers (i would like to download the file and put it on a sony mp3 player - not subscribe.

#### Steps to reproduce the problem
update podcast section on the website.  Thank you.

**Comment by archon810** [comment]
Hi @shaz213,

Are you strictly talking about this page http://www.androidpolice.com/topics/podcast/?

I recommend you subscribe using one of the methods described in each podcast post instead. Dedicated AP podcast posts are not guaranteed and are only made very rarely.
