### ISSUE TITLE
Search bar visible when it shouldn't be above title bar in Safari on iPhone SE

### ISSUE THREAD

**Issue by sensi277** [archon810/androidpolice-public#81]
#### Expected behavior
Search bar is not visible until search button is tapped.

#### Actual behavior
Search bar is visible when attempting to scroll above page before bounce-back, or while quickly scrolling to top of page.

[Here's a video demonstrating the issue.](https://github.com/archon810/androidpolice-public/files/1066186/AP.iOS.Safari.Bug.zip)

#### Steps to reproduce the problem
1. Load AP on iOS.
2. Attempt to scroll up past the top of the page.
3. ...Profit? (no, just kidding, you fix the bug of course)

This isn't really a bug per se (the site is functioning perfectly), but it is an example of what can go wrong when a browser does something unorthodox _like let you scroll above the top of the page._

E: Just changed the title to clarify that this is on an iPhone SE running the latest version of iOS (10.3.2).

**Comment by archon810** [comment]
@sensi277 The fix for this issue has been rolled out, along with tweaks to Safari's search box style. Can you please test, as I don't have a Mac myself.
