### ISSUE TITLE
Previous (k) / Next (j) hotkey navigation issue when on sub-site

### ISSUE THREAD

**Issue by yoakster314** [archon810/androidpolice-public#84]
I love the fact I can browse articles on your site with hotkeys.  However, there is a small bug that I encountered.

#### Expected behavior
When I get to the end of a subtopic (say deals: http://www.androidpolice.com/topics/deals/) and I click the "j" key to advance to the next article, it should take me to the 2nd page of the subtopic (say: http://www.androidpolice.com/topics/deals/page/2/).

#### Actual behavior
Clicking "j" at the end of the deals page (http://www.androidpolice.com/topics/deals/) takes me to the 2nd page of the main article feed (http://www.androidpolice.com/page/2/)

#### Steps to reproduce the problem

- Start on the homepage (http://www.androidpolice.com/)
- Click on any of the subtopics ("Leaks", "Exclusives", "Downloads", "Deals", "Giveaways", "Features", "Editorials").
- That will bring you to a page with a URL like this (http://www.androidpolice.com/topics/deals/)
- Navigate down the page using the "J" key.
- Once you get to the end of the page, pressing the "J" key should take you to the next page in that series.
- However, instead it takes you to the second page of the main feed (http://www.androidpolice.com/page/2/)

Note: This only happens when starting on the first page of the subtopic (http://www.androidpolice.com/topics/deals/).  If you manually go to the second page of a subtopic (http://www.androidpolice.com/topics/deals/page/2/) and use the "J" key to progress to further pages, it works as expected.

**Comment by archon810** [comment]
Thanks for the detailed report and the reproduction steps. I've reproduced and will take a look.

**Comment by archon810** [comment]
Fixed and pushed to production. Thanks for reporting the bug.

**Comment by yoakster314** [comment]
No problem, happy to help.  Thanks for the quick turnaround.  Works like a charm now! :)
