### ISSUE TITLE
Tweeting an article should be able to use more text

### ISSUE THREAD

**Issue by Stanzilla** [archon810/androidpolice-public#85]
#### Expected behavior
Prefilled text in tweet window includes the whole headline

#### Actual behavior
Prefilled text in tweet window does not include the whole headline and is cut off

#### Steps to reproduce the problem

* Go to http://www.androidpolice.com/2017/07/08/google-says-allo-desktop-client-coming-weeks/
* Click the "Tweet" button

Currently I get
```
Google says the Allo desktop client is coming in a  http://www.androidpolice.com/2017/07/08/google-says-allo-desktop-client-coming-weeks/
```

I guess this implementation is from a time before Twitter removed URLs from the character limit, but it should be possible to include the whole article headline in the Tweet now.

**Comment by archon810** [comment]
The bug here seems to be an improper escaping of the quote rather than the length of the title. I'll take a look, thanks.

**Comment by archon810** [comment]
The fix has been rolled out.
