### ISSUE TITLE
Wrong image associated with an article when posted on LinkedIn

### ISSUE THREAD

**Issue by pflefaou** [archon810/androidpolice-public#86]
#### Expected behavior
When posted on LinkedIn, http://www.androidpolice.com/2017/07/20/pioneers-three-2017-android-auto-head-units-including-single-din-model-now-available-multiple-retailers/ is associated with the actual picture shown on top of the article.

#### Actual behavior
The associated picture is different. I contacted LinkedIn and they say it's not their fault, it's the website's choice.

#### Steps to reproduce the problem
100% reproducible when posting that article, be it on mobile or on the web.

**Comment by archon810** [comment]
I've looked into it, and it looks like the image LinkedIn (and Facebook) uses comes from a previous version of the story that they cached. The image is http://www.androidpolice.com/wp-content/uploads/2017/07/nexus2cee_singledin-728x473.png, which is no longer in the article, as you can see.

Facebook, when forced to refresh by appending something like ?abc to the url of the shared story, correctly shows only the new image. However, LinkedIn seems to ignore url params and insists on using an older cached version of the page.

This is not a problem with AP, but rather a refusal by LinkedIn to update their cached version of the page, which is silly. G+, for example, caches urls per user, so it didn't have any issues pulling up the right version right away.
