### ISSUE TITLE
Create an Android app for this website please

### ISSUE THREAD

**Issue by tushar260** [archon810/androidpolice-public#88]

**Comment by archon810** [comment]
Sorry, we have no plans to create an app.

**Comment by moriel5** [comment]
How about an AndroidPolice/APKMirror app?
Since there may eventually be an APKMirror app.

**Comment by archon810** [comment]
We have no active plans to create either app.

**Comment by moriel5** [comment]
!!!
So all the teases were nothing more than teases?
I had really been fooled the past few years.

**Comment by archon810** [comment]
Heh, I believe Cody started on something, but it never got traction. I don't have interest in Android apps for sites, and there's no project to make either of them and then maintain them.

**Comment by moriel5** [comment]
In any case, I am sorry that my näivete had caused this confusion.

I may not comment as often as in the past (due to not being able to comment as a guest, however I understand the neccessity of disabling that feature), however I am still an avid reader of AndroidPolice)
